### ISSUE TITLE
Current Release PHP Fatal Error!

### ISSUE THREAD

**Issue by michaelrimbach** [woocommerce/woocommerce-gateway-klarna#130]
Please don't list this plugin here if its not working.

### Klarna plugin version

- 2.5.14

### WordPress version

- 4.9.8

### WooCommerce version

- 3.5.1

### Klarna country

- Germany

Nov 21 17:24:41 xyz [21-Nov-2018 17:24:41 UTC] PHP Fatal error:  Uncaught Error: Class 'Klarna_Checkout_For_Woocommerce_GDPR' not found in /wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-gdpr.php:43

**Comment by NiklasHogefjord** [comment]
Hi,

You have a valid point. We will remove the plugin from this repository since it's not updated here anymore.

However, the plugin is still maintained but it is handled in this repository since it's no longer distributed via woocommerce.com - https://github.com/krokedil/woocommerce-gateway-klarna/releases.

From version 2.6.0 automatic updates works better than with your current version. Please update to the latest version. I think that will solve your problem.
