### ISSUE TITLE
Change payment method with saved stripe credit card not working

### ISSUE THREAD

**Issue by michaelrimbach** [woocommerce/woocommerce-gateway-klarna#43]
### Expected behavior

Change payment method by clicking on them. 

### Actual behavior

When changing the payment method the payment method jump back to the last selected one. So its not possible to use another payment method than "woocommerce-gateway-stripe" (https://github.com/woocommerce/woocommerce-gateway-stripe - newest version).

I found out that its only not working if I have a saved credit card in my account (and have enabled " Enable Payment via Saved Cards" at the stripe plugin). I think this is a javascript bug.

### Steps to reproduce the behavior

See the video:
[https://picload.org/image/rddacrgg/2016-09-2817h00_38.gif](url)

After trying to change the payment method, I deactivated the Klarna plugin and than it works as expected (as you can see in the video).

### WordPress version

4.5.4

### WooCommerce version

2.6.4

### Klarna country

Germany

**Comment by slobodan** [comment]
@michaelrimbach we're working on a fix for this, can you temporarily try commenting out this line in classes/class-klarna-invoice.php:

`$('body').trigger('update_checkout');`

Should be at line 785, and just needs to be changed to:

`// $('body').trigger('update_checkout');`

Please let me know if that worked, we'll have it fixed in next version of our plugin.

Did this start happening after an update to one of the plugins you're using?

**Comment by michaelrimbach** [comment]
Thanks, that do the trick.

I cant say if its update related, because we switched from the braintree to the stripe payment plugin. So we dont use the stripe plugin together with klarna before.
