### ISSUE TITLE
Refund button error: This order cannot be refunded. Please make sure it is activated

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-klarna#49]
### Expected behavior

The Klarna plugin doesn't handle automatic refunds - all refunds must be processed via the Klarna dashboard. 

However, once an order is in the `processing` or `completed` state, the Refund button returns the error `This order cannot be refunded. Please make sure it is activated`. The log shows `10-19-2016 @ 11:10:56 - Refund Failed: No Klarna invoice ID.`

Alternatively, this status should be available in the list of order statuses so that it can be selected there. 
### Actual behavior

Once an order is in the `processing` or `completed status`, there is no way to manually mark the order as refunded:
- The Refund button returns an error
- "Refunded" is not an option in the list of order statuses

The only way to manually mark the order as refunded is to disable the Klarna gateway plugin, mark the order as refunded and then re-enable the plugin.
### Steps to reproduce the behavior
1. Check out using Klarna Checkout
2. Ensure the order status is `Processing` or `Completed`
3. Try to refund the order.

Reproduced on the customer's live site, customer's staging site and my own test site.
### WordPress version

4.6.1
### WooCommerce version

2.6.4
### Klarna country

Norway (also tested with Swedish credentials)

479246-zd-woothemes

**Comment by slobodan** [comment]
Hi @hannahswain 

In order to automatically process the refund in Klarna's system, WooCommerce order has to be marked "Completed", with "Activate Klarna order automatically when WooCommerce order is marked complete" checkbox in Klarna Checkout settings checked.

If you do this, and then process the refund in WooCommerce, then WooCommerce order will be marked "Refunded" automatically. From how you described the issue, I think this will solve your problem. Please let me know if that does the trick.

It is not possible to set a WooCommerce to "Refunded" by changing the status in the dropdown because that's how Klarna requested it to be. The reason was that allowing this to be done could potentially cause many WooCommerce order to be out of sync with Klarna.

You can however overcome this by using 'klarna_checkout_hide_refunded_status' filter, returning false. Doing that will let you select "Refunded" status in the dropdown.
